name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Step 4: Run Tests and Generate Coverage Report
      - name: Run Tests and Coverage
        run: |
          pytest --cov=devops_tasks --cov-report=xml
          mv coverage.xml pytest-coverage.xml

      # Step 5: Verify Coverage File
      - name: Verify Coverage File
        run: ls -l pytest-coverage.xml || echo "Coverage file not found"

      # Step 6: Run SonarCloud Analysis Using Generated Coverage Report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Rimesp_devops-tasks-tests
            -Dsonar.organization=rimesp123
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=pytest-coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 7: Upload Coverage Report as Artifact (Optional)
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-coverage-report
          path: pytest-coverage.xml
