name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-cov

      # Step 4: Run Tests and Generate Coverage Report
      - name: Run Tests
        run: |
          pytest --cov=devops_tasks --cov-report=xml
          mv coverage.xml pytest-coverage.xml

      # Step 5: Set Up Java Environment (Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 6: Download and Set Up SonarScanner
      - name: Download SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip -q sonar-scanner-cli.zip
          mv sonar-scanner-4.7.0.2747-linux $HOME/sonar-scanner

      # Step 7: Set JAVA_HOME Globally
      - name: Set Java Environment
        run: echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64" >> $GITHUB_ENV

      # Step 8: Verify Java Version
      - name: Verify Java Version
        run: java -version

      # Step 9: Run SonarCloud Analysis
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
        run: |
          $HOME/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=Rimesp_devops-tasks-tests \
            -Dsonar.organization=rimesp \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.coverage.reportPaths=pytest-coverage.xml
