name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-cov

      - name: Run Tests
        run: |
          pytest --cov=devops_tasks --cov-report=xml
          mv coverage.xml pytest-coverage.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Java Environment
        run: |
          echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Java Version
        run: java -version

      - name: Install Shell Utilities
        run: sudo apt-get update && sudo apt-get install -y shellcheck unzip

      - name: Download SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip -q sonar-scanner-cli.zip
          mv sonar-scanner-4.7.0.2747-linux $HOME/sonar-scanner
          echo "PATH=$HOME/sonar-scanner/bin:$PATH" >> $GITHUB_ENV

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          $HOME/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=Rimesp_devops-tasks-tests \
            -Dsonar.organization=rimesp \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.coverage.reportPaths=pytest-coverage.xml
