name: CI/CD Pipeline for DevOps Tasks

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python (for pytest tests)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Install Python dependencies and run tests
    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest --cov=devops_tasks --cov-report=xml

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: docker build -t rrim/devops-tasks-tests:latest .

    # Step 6: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push rrim/devops-tasks-tests:latest
