name: CI/CD Pipeline for DevOps Tasks

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python (for pytest tests)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    # Step 3: Install Python dependencies and run tests
    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest --cov=devops_tasks --cov-report=xml
  
    # Step 4: CodeClimate Test Reporter Integration
    - name: Upload coverage to CodeClimate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        ./cc-test-reporter after-build --exit-code $?
  
    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  
    # Step 6: Build the Docker image
    - name: Build Docker image
      run: docker build -t rrim/devops-tasks-tests:latest .
  
    # Step 7: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push rrim/devops-tasks-tests:latest

      # Step 8: Install Railway CLI
    - name: Install Railway CLI
      run: curl -fsSL https://railway.app/install.sh | sh

    # Step 9: Deploy to Railway
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway login
        railway up --service devops-tasks
        # Step 10: Health Check
    - name: Health Check
      run: |
        curl -f https://your-railway-app-url.com/health || exit 1
