name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch Full Git History
      - name: Fetch all history for all branches
        run: git fetch --unshallow

      # Step 3: Set Up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 4: Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Step 5: Run Tests and Generate Coverage Report
      - name: Run Tests and Coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-config=.coveragerc
          mv coverage.xml pytest-coverage.xml

      # Step 6: Verify Coverage File
      - name: Verify Coverage File
        run: |
          if [ ! -f pytest-coverage.xml ]; then
            echo "Coverage file not found!"
            exit 1
          fi
          echo "Coverage file found: pytest-coverage.xml"

      # Step 7: Run SonarCloud Analysis Using Generated Coverage Report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Rimesp_devops-tasks-tests
            -Dsonar.organization=rimesp123
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=pytest-coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
