name: CI/CD Pipeline for DevOps Tasks

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python (for pytest tests)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    # Step 3: Install Python dependencies and run tests
    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest --cov=devops_tasks --cov-report=xml
  
    # Step 4: SonarQube Analysis
    - name: Sonarless Code Scan
      uses: gitricko/sonarless@v1.2
      with:
        sonar-source-path: ''
        sonar-project-name: ''
        sonar-project-key: ''
        sonar-metrics-path: './'
  
    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  
    # Step 6: Build the Docker image
    - name: Build Docker image
      run: docker build -t rrim/devops-tasks-tests:latest .
  
    # Step 7: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push rrim/devops-tasks-tests:latest
